In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
from src.frost import fetch_observations, parse_hourly_observations

In [3]:
data = fetch_observations(
    source="SN18700",
    elements=[
        "air_temperature",
        "relative_humidity",
        "wind_speed",
    ],
    start_date="2025-01-01",
    end_date="2025-01-03",
)

In [4]:
rows = parse_hourly_observations(data)

In [5]:
rows[:3]

[{'timestamp': '2025-01-01T00:00:00.000Z',
  'air_temperature': -3.5,
  'relative_humidity': 81,
  'wind_speed': 6.8},
 {'timestamp': '2025-01-01T01:00:00.000Z',
  'air_temperature': -3.7,
  'relative_humidity': 81,
  'wind_speed': 6},
 {'timestamp': '2025-01-01T02:00:00.000Z',
  'air_temperature': -4.2,
  'relative_humidity': 85,
  'wind_speed': 6.6}]

In [6]:
import pandas as pd

df = pd.DataFrame(rows)

In [7]:
df.head(10)

                  timestamp  air_temperature  relative_humidity  wind_speed
0  2025-01-01T00:00:00.000Z             -3.5                 81         6.8
1  2025-01-01T01:00:00.000Z             -3.7                 81         6.0
2  2025-01-01T02:00:00.000Z             -4.2                 85         6.6
3  2025-01-01T03:00:00.000Z             -4.0                 78         6.4
4  2025-01-01T04:00:00.000Z             -4.2                 78         6.8
5  2025-01-01T05:00:00.000Z             -4.5                 80         4.3
6  2025-01-01T06:00:00.000Z             -4.8                 81         3.4
7  2025-01-01T07:00:00.000Z             -4.8                 80         2.1
8  2025-01-01T08:00:00.000Z             -5.2                 79         2.3
9  2025-01-01T09:00:00.000Z             -4.8                 76         2.8

In [8]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          48 non-null     datetime64[us, UTC]
 1   air_temperature    48 non-null     float64
 2   relative_humidity  48 non-null     int64
 3   wind_speed         48 non-null     float64
dtypes: datetime64[us, UTC](1), float64(2), int64(1)
memory usage: 1.6 KB

In [10]:
df.isna().sum()

timestamp            0
air_temperature      0
relative_humidity    0
wind_speed           0
dtype: int64

In [11]:
from pathlib import Path

output_path = Path("../data/processed/frost_hourly_sample.csv")
df.to_csv(output_path, index=False)

In [12]:
output_path.exists()

True

In [13]:
pd.read_csv(output_path).head()

                   timestamp  air_temperature  relative_humidity  wind_speed
0  2025-01-01 00:00:00+00:00             -3.5                 81         6.8
1  2025-01-01 01:00:00+00:00             -3.7                 81         6.0
2  2025-01-01 02:00:00+00:00             -4.2                 85         6.6
3  2025-01-01 03:00:00+00:00             -4.0                 78         6.4
4  2025-01-01 04:00:00+00:00             -4.2                 78         6.8